services:
  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: pdfme-rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./RabbitMQ/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    networks:
      - pdfme-network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: pdfme-minio
    hostname: minio
    ports:
      - "9000:9000"    # API port
      - "9001:9001"    # Console UI
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - pdfme-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: pdfme-postgres
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: pdfme
      POSTGRES_USER: pdfme
      POSTGRES_PASSWORD: pdfme_secure_pass
      POSTGRES_INITDB_ARGS: "-E UTF8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db-simplified.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    command: postgres -c max_connections=400 -c shared_buffers=512MB -c effective_cache_size=1536MB -c listen_addresses='*'
    networks:
      - pdfme-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pdfme -d pdfme"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: pdfme-redis
    hostname: redis
    ports:
      - "6379:6379"
    command: >
      redis-server
      --maxmemory 2gb
      --maxmemory-policy allkeys-lru
      --proto-max-bulk-len 256mb
      --client-output-buffer-limit normal 0 0 0
      --save 60 1000
      --appendonly yes
      --appendfsync everysec
    volumes:
      - redis_data:/data
    networks:
      - pdfme-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  pdf-generator:
    build:
      context: ./pdfme
      dockerfile: Dockerfile
    container_name: pdfme-generator
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - RABBITMQ_URL=amqp://admin:admin123@rabbitmq:5672
      - DEFAULT_BUCKET=pdfs
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=pdfme
      - POSTGRES_PASSWORD=pdfme_secure_pass
      - POSTGRES_DB=pdfme
      - POSTGRES_MAX_POOL_SIZE=20
      - POSTGRES_MIN_POOL_SIZE=5
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - pdfme-network
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  storage-service:
    build:
      context: ./storage-service
      dockerfile: Dockerfile
    container_name: pdfme-storage
    environment:
      - RABBITMQ_URL=amqp://admin:admin123@rabbitmq:5672
      - QUEUE_NAME=storage_ready
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_USE_SSL=false
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=pdfme
      - POSTGRES_PASSWORD=pdfme_secure_pass
      - POSTGRES_DB=pdfme
      - POSTGRES_MAX_POOL_SIZE=10
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - pdfme-network
    depends_on:
      rabbitmq:
        condition: service_healthy
      minio:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  file-watcher:
    build:
      context: ./file-watcher
      dockerfile: Dockerfile
    container_name: pdfme-file-watcher
    environment:
      - RABBITMQ_URL=amqp://admin:admin123@rabbitmq:5672
      - QUEUE_NAME=parse_ready
      - BUCKET_NAME=uploads
      - POLL_INTERVAL=10s
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_USE_SSL=false
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=pdfme
      - POSTGRES_PASSWORD=pdfme_secure_pass
      - POSTGRES_DB=pdfme
      - POSTGRES_MAX_POOL_SIZE=10
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - BATCH_SIZE=100
      - RATE_LIMIT_PER_SECOND=50
    networks:
      - pdfme-network
    depends_on:
      rabbitmq:
        condition: service_healthy
      minio:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  parser-service:
    build:
      context: ./parser
      dockerfile: Dockerfile
    container_name: pdfme-parser
    ports:
      - "8080:8080"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=admin123
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=pdfme
      - POSTGRES_PASSWORD=pdfme_secure_pass
      - POSTGRES_DB=pdfme
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE=15
      - SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE=5
    networks:
      - pdfme-network
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

volumes:
  rabbitmq_data:
  minio_data:
  postgres_data:
  redis_data:

networks:
  pdfme-network:
    driver: bridge
