---
apiVersion: v1
kind: ConfigMap
metadata:
  name: file-watcher-config
  namespace: pdfme
data:
  QUEUE_NAME: "parse_ready"
  BUCKET_NAME: "uploads"
  POLL_INTERVAL: "10s"
  MINIO_ENDPOINT: "minio:9000"
  MINIO_USE_SSL: "false"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "pdfme"
  POSTGRES_MAX_POOL_SIZE: "10"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  BATCH_SIZE: "100"
  RATE_LIMIT_PER_SECOND: "50"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-watcher
  namespace: pdfme
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-watcher
  template:
    metadata:
      labels:
        app: file-watcher
    spec:
      containers:
      - name: file-watcher
        image: pdfme-file-watcher:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: RABBITMQ_URL
          value: "amqp://$(RABBITMQ_USER):$(RABBITMQ_PASS)@rabbitmq:5672"
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: username
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: password
        - name: QUEUE_NAME
          valueFrom:
            configMapKeyRef:
              name: file-watcher-config
              key: QUEUE_NAME
        - name: BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: file-watcher-config
              key: BUCKET_NAME
        - name: POLL_INTERVAL
          valueFrom:
            configMapKeyRef:
              name: file-watcher-config
              key: POLL_INTERVAL
        - name: MINIO_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: file-watcher-config
              key: MINIO_ENDPOINT
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: root-user
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: root-password
        - name: MINIO_USE_SSL
          valueFrom:
            configMapKeyRef:
              name: file-watcher-config
              key: MINIO_USE_SSL
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: file-watcher-config
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: file-watcher-config
              key: POSTGRES_PORT
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: database
        - name: POSTGRES_MAX_POOL_SIZE
          valueFrom:
            configMapKeyRef:
              name: file-watcher-config
              key: POSTGRES_MAX_POOL_SIZE
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: file-watcher-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: file-watcher-config
              key: REDIS_PORT
        - name: BATCH_SIZE
          valueFrom:
            configMapKeyRef:
              name: file-watcher-config
              key: BATCH_SIZE
        - name: RATE_LIMIT_PER_SECOND
          valueFrom:
            configMapKeyRef:
              name: file-watcher-config
              key: RATE_LIMIT_PER_SECOND
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
