---
apiVersion: v1
kind: Secret
metadata:
  name: parser-secret
  namespace: eps
type: Opaque
stringData:
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USERNAME: "admin"
  RABBITMQ_PASSWORD: "admin123"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "pdfme"
  POSTGRES_PASSWORD: "pdfme_secure_pass"
  POSTGRES_DB: "pdfme"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: parser-config
  namespace: eps
data:
  SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: "15"
  SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: "5"
---
apiVersion: v1
kind: Service
metadata:
  name: parser-service
  namespace: eps
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: parser
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: parser
  namespace: eps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parser
  template:
    metadata:
      labels:
        app: parser
    spec:
      containers:
      - name: parser
        image: gwynbliedd/pdfme-parser:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        envFrom:
        - configMapRef:
            name: parser-config
        - secretRef:
            name: parser-secret
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
