---
apiVersion: v1
kind: ConfigMap
metadata:
  name: parser-service-config
  namespace: pdfme
data:
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "pdfme"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: "15"
  SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: "5"
---
apiVersion: v1
kind: Service
metadata:
  name: parser-service
  namespace: pdfme
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: parser-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: parser-service
  namespace: pdfme
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parser-service
  template:
    metadata:
      labels:
        app: parser-service
    spec:
      containers:
      - name: parser-service
        image: pdfme-parser:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: parser-service-config
              key: RABBITMQ_HOST
        - name: RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              name: parser-service-config
              key: RABBITMQ_PORT
        - name: RABBITMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: username
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: password
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: parser-service-config
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: parser-service-config
              key: POSTGRES_PORT
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: database
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: parser-service-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: parser-service-config
              key: REDIS_PORT
        - name: SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE
          valueFrom:
            configMapKeyRef:
              name: parser-service-config
              key: SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE
        - name: SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE
          valueFrom:
            configMapKeyRef:
              name: parser-service-config
              key: SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
