---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pdf-generator-config
  namespace: pdfme
data:
  NODE_ENV: "production"
  DEFAULT_BUCKET: "pdfs"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "pdfme"
  POSTGRES_MAX_POOL_SIZE: "20"
  POSTGRES_MIN_POOL_SIZE: "5"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: pdf-generator
  namespace: pdfme
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    app: pdf-generator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-generator
  namespace: pdfme
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdf-generator
  template:
    metadata:
      labels:
        app: pdf-generator
    spec:
      containers:
      - name: pdf-generator
        image: pdfme-generator:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: pdf-generator-config
              key: NODE_ENV
        - name: RABBITMQ_URL
          value: "amqp://$(RABBITMQ_USER):$(RABBITMQ_PASS)@rabbitmq:5672"
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: username
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: password
        - name: DEFAULT_BUCKET
          valueFrom:
            configMapKeyRef:
              name: pdf-generator-config
              key: DEFAULT_BUCKET
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: pdf-generator-config
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: pdf-generator-config
              key: POSTGRES_PORT
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: database
        - name: POSTGRES_MAX_POOL_SIZE
          valueFrom:
            configMapKeyRef:
              name: pdf-generator-config
              key: POSTGRES_MAX_POOL_SIZE
        - name: POSTGRES_MIN_POOL_SIZE
          valueFrom:
            configMapKeyRef:
              name: pdf-generator-config
              key: POSTGRES_MIN_POOL_SIZE
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: pdf-generator-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: pdf-generator-config
              key: REDIS_PORT
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
