---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: pdfme
type: Opaque
stringData:
  username: pdfme
  password: pdfme_secure_pass
  database: pdfme
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: pdfme
data:
  POSTGRES_INITDB_ARGS: "-E UTF8"
  # Note: Mount your init-db-simplified.sql as a ConfigMap or use initdb scripts
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: pdfme
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: pdfme
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      hostname: postgres
      containers:
      - name: postgres
        image: postgres:16-alpine
        ports:
        - containerPort: 5432
          name: postgres
        args:
        - -c
        - max_connections=400
        - -c
        - shared_buffers=512MB
        - -c
        - effective_cache_size=1536MB
        - -c
        - listen_addresses=*
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: database
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: POSTGRES_INITDB_ARGS
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_INITDB_ARGS
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        # Uncomment below if you want to mount init SQL script
        # - name: init-script
        #   mountPath: /docker-entrypoint-initdb.d/01-init.sql
        #   subPath: 01-init.sql
        #   readOnly: true
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready -U pdfme -d pdfme
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready -U pdfme -d pdfme
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
      volumes:
      # Uncomment below if you want to mount init SQL script
      # - name: init-script
      #   configMap:
      #     name: postgres-init-script
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi
---
# Uncomment and populate with your init SQL if needed
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: postgres-init-script
#   namespace: pdfme
# data:
#   01-init.sql: |
#     -- Your init SQL here
