---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: pdfme
data:
  valkey.conf: |
    # Maximum memory limit - Valkey will use up to 2GB of RAM
    maxmemory 2gb

    # Eviction policy when maxmemory is reached - removes least recently used keys
    maxmemory-policy allkeys-lru

    # Maximum size of a single request/response (256MB for large PDF blobs)
    proto-max-bulk-len 256mb

    # Disable output buffer limits for normal clients (no memory limits on responses)
    client-output-buffer-limit normal 0 0 0
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: pdfme
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: pdfme
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      hostname: redis
      containers:
      - name: redis
        image: valkey/valkey:7-alpine
        command:
        - valkey-server
        - /etc/valkey/valkey.conf
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - name: redis-config
          mountPath: /etc/valkey
          readOnly: true
        livenessProbe:
          exec:
            command:
            - valkey-cli
            - ping
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - valkey-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "500m"
      volumes:
      - name: redis-config
        configMap:
          name: redis-config
